name: mvimg
description: A library to split mvimg(android motion video) file.
version: 1.4.0
repository: https://github.com/caijinglong/mvimg

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  buff: ^1.0.1
  collection: ^1.0.0
  xml: ^6.4.2
